### ISSUE TITLE
Error in Test the model with your pre-trained weights

### ISSUE THREAD

**Issue by newZachary** [cvlab-yonsei/RRID#7]
Hi, 
I have trained your pth, and tried to run evaluate.py.  
But I got errors. The error message is: AttributeError: 'DataParallel' object has no attribute 'src_device_obj'. 
I don't find the attribute 'src_device_obj'.

The complete error:
Extracting features... This may take a while...
Traceback (most recent call last):
  File "Evaluate.py", line 94, in <module>
    final_feat_list, _, _, _, _, = model(Variable(imgs).cuda())
  File "/home/stu/.conda/envs/pytorch2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/stu/.conda/envs/pytorch2/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 151, in forward
    if t.device != self.src_device_obj:
  File "/home/stu/.conda/envs/pytorch2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 948, in __getattr__
    type(self).__name__, name))
AttributeError: 'DataParallel' object has no attribute 'src_device_obj'

I tried many times but couldn't solve it. 
Counld you please help me? Thanks a lot!

**Comment by aryachiranjeev** [comment]
Hi @newZachary would you able to solve this error?
